### ISSUE TITLE
Incompatibility with backend lead to my JS animations not working.

### ISSUE THREAD

**Issue by gauravjk108** [gauravjk108/AnnapurnaHotelGroup3#1]
Please check the django compatibilty with my frontend. The animations doesn't seem to be working.

**Comment by aazadkhadka** [comment]
Yes, only the homepage of react js is rendering on my screen as well. Since deadline is due soon, let's drop ReactJS and use HTML CSS instead. PHP will be used for backend as it as excellent synergy with HTML
![Screenshot (603)](https://user-images.githubusercontent.com/81901308/114973700-b1cead00-9ea0-11eb-8451-02ffbe3ebdd7.png)

**Comment by gauravjk108** [comment]
Okay seems like a way to go. I was questioning the same thing as well. I am glad that we are on the same page.
