### ISSUE TITLE
Inconsistent UI of Admin Login page

### ISSUE THREAD

**Issue by Sopnil100** [gauravjk108/AnnapurnaHotelGroup3#13]
Assigned to: @gauravjk108

**Comment by gauravjk108** [comment]
Can I learn which part of the  UI is incosistent?

**Comment by gauravjk108** [comment]
I remember using the same layout, grids and CSS for the login page as well.

**Comment by Sopnil100** [comment]
![Screenshot (660)](https://user-images.githubusercontent.com/81901457/118351564-7cd77800-b57c-11eb-85c1-4121322685c9.png)

This interface is different compared to others.

**Comment by gauravjk108** [comment]
I see the problem seems to be that during the backend integration, an outdated JS was used which is now fixed and now I have tweaked the files to fix it. It now looks like this:
![image](https://user-images.githubusercontent.com/81900709/118351652-db045b00-b57c-11eb-9861-8a95ee8bb3ca.png)

I request you to check again, it should be fixed.

**Comment by Sopnil100** [comment]
I have reviewed the page again and it is fixed. The issue is closed. Thank you.
