### ISSUE TITLE
Error message on successful reservation

### ISSUE THREAD

**Issue by Sopnil100** [gauravjk108/AnnapurnaHotelGroup3#14]
Assigned to: @gauravjk108

**Comment by gauravjk108** [comment]
Can I see some screenshot? I can't seem to replicate the bug you are talking about.

**Comment by Sopnil100** [comment]
I have included screenshots and steps to reproduce the bug in the following document.
[Error message on successful reservation.docx](https://github.com/gauravjk108/AnnapurnaHotelGroup3/files/6483684/Error.message.on.successful.reservation.docx)

**Comment by gauravjk108** [comment]
I have tracked the bug and it seems to appear because of use of an outdated JS and I have replaced it with a new PHP component which should be echoed by the methods every time the POST function is called. You will no longer see the Error on form submission. Except you will be redirected to this echoes component by the PHP.
![image](https://user-images.githubusercontent.com/81900709/118351949-764a0000-b57e-11eb-9c48-a5b219fb3c0f.png)
Please verify the bug fix. Thank you.

**Comment by Sopnil100** [comment]
I have re-checked the issue and it seems to be resolved. The issue is now closed. Thank you.
